server:
  port: 8080
  context-path: /kafka
spring:
  profiles:
    active: dev
kafka:
  topic:
    group-id: topicGroupId
    topic-name:
      - topic1
      - topic2
      - topic3
      - Hellow-table
      - my-topic
logging:
  config: classpath:logback.xml